parameters:
    twig.loader.filesystem.class: Glory\ThemeBundle\Loader\TwigLoader
services:
    glory_theme.listener:
        class: Glory\ThemeBundle\EventListener\ThemeListener
        arguments: [@service_container]
        tags:
            -  { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

#    glory_theme.twig.loader:
#        class: Glory\ThemeBundle\Loader\TwigLoader
#        arguments: [@templating.locator, @templating.name_parser]
#        tags:
#            - { name: twig.loader }
#    twig.loader.filesystem:
#        alias: glory_theme.twig.loader

    glory_theme.manager:
        class: Glory\ThemeBundle\Manager\ThemeManager
        arguments: [@service_container]
        
    glory_theme.theme.locator:
        class: Glory\ThemeBundle\Locator\ThemeLocator
        arguments: [@kernel, @glory_theme.manager, @file_locator]

    glory_theme.templating.locator:
        class: Glory\ThemeBundle\Locator\TemplatingLocator
        arguments: [@glory_theme.theme.locator, %kernel.cache_dir%]

    templating.locator:
        alias: glory_theme.templating.locator